
test_input = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""


def part_one(input_str):
    matr = [list(row) for row in input_str.split()]

    split = 0
    for m in range(1, len(matr)):
        for n in range(len(matr[0])):
            if matr[m-1][n] == "S" or matr[m-1][n] == "|":
                # splitters can't stand next to each other (luckily) and there are no splitters on the sidelines
                if matr[m][n] == "^":
                    split += 1
                    matr[m][n-1] = "|"
                    matr[m][n+1] = "|"
                else: #empty space
                    matr[m][n] = "|"
    return split


with open("Day7.txt", "r") as file:
    actual_input = file.read()

print(part_one(actual_input))


